sonar.projectKey=Proyecto-Horarios-UC
sonar.projectName=Proyecto Horarios UC
sonar.projectVersion=1.0
sonar.sourceEncoding=UTF-8

# Directories to analyze
sonar.sources=backend/src,frontend/src
sonar.exclusions=**/node_modules/**,**/dist/**,**/build/**,**/*.test.js,**/*.test.ts,**/*.test.tsx,**/*.spec.js,**/*.spec.ts,**/*.spec.tsx,frontend/vite.config.ts

# Tests configuration
sonar.tests=backend/src,frontend/src
sonar.test.inclusions=**/*.test.js,**/*.test.ts,**/*.test.tsx,**/*.spec.js,**/*.spec.ts,**/*.spec.tsx

# Coverage
sonar.javascript.lcov.reportPaths=backend/coverage/lcov.info,frontend/coverage/lcov.info

# Wait for quality gate
sonar.qualitygate.wait=true

sonar.host.url=http://host.docker.internal:9000
sonar.login=admin
sonar.password=admin123
